### ISSUE TITLE
Label not found error in STORESHIP command

### ISSUE THREAD

**Issue by DMC73120** [TW2002/mombot#33] opened 2022-12-28 11:26 UTC
Sparky — Today at 5:20 AM
this happens occasionally when running storeship

![image](https://user-images.githubusercontent.com/74340253/209804818-d08f86b3-33ba-47a6-b380-d292d5a887a2.png)

**Comment by RogerHuba** [comment] 2022-12-28 20:22
duplicate of #14

**Closed as completed by RogerHuba** 2022-12-28 20:22 UTC
Labels: bug
